name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia √† meia-noite (UTC)
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do reposit√≥rio
        uses: actions/checkout@v3

      - name: Gerar a cobrinha üêç
        uses: Platane/snk@v3
        with:
          github_user_name: im-JessicaV
          outputs: dist/snake.svg

      - name: Deploy no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
